// SPDX-License-Identifier: MIT OR Apache-2.0

//! Code generator: [`Schema`] AST -> Rust source targeting
//! the `tpt-asn1-core` `Decode`/`Encode` traits.

use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;

use crate::ast::*;
use crate::error::{CompilerError, Result};

/// Generate Rust source code for `schema`.
pub fn generate(schema: &Schema) -> Result<String> {
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by tpt-asn1-compiler from module `{}`. Do not edit.\n",
        schema.module
    ));
    out.push_str("#![allow(unused_imports, non_camel_case_types, unused_lifetimes, clippy::all)]\n");
    out.push_str(
        "use tpt_asn1_core::{\n    reader::{Reader, EncodingRule, Config},\n    decode::{Decode, Encode, read_sequence, read_set, read_sequence_of, read_set_of, read_sequence_of_content, read_set_of_content, retag_implicit, encode_to_vec},\n    tag::{Tag, Class},\n    writer::{Writer, WriteBackend},\n    types::*,\n    any::Any,\n    error::{Error, Result},\n    length::Length,\n    Vec,\n};\n\n",
    );

    for ta in &schema.types {
        out.push_str(&generate_type(&ta.name, &ta.def, &schema.types)?);
        out.push_str("\n");
    }

    Ok(out)
}

fn lookup<'a>(name: &str, types: &'a [TypeAssignment]) -> Option<&'a TypeDef> {
    types.iter().find(|t| t.name == name).map(|t| &t.def)
}

fn def_has_lifetime(def: &TypeDef, types: &[TypeAssignment]) -> bool {
    match def {
        TypeDef::Sequence(_) | TypeDef::Set(_) | TypeDef::Choice(_) => true,
        TypeDef::Enumerated(_) => false,
        TypeDef::Alias(t) => type_has_lifetime(t, types),
    }
}

fn type_has_lifetime(ty: &Type, types: &[TypeAssignment]) -> bool {
    match ty {
        Type::Named(name) => def_has_lifetime(lookup(name, types).unwrap(), types),
        Type::Builtin(b) => builtin_has_lifetime(*b),
        Type::Sequence(_) | Type::Set(_) | Type::Choice(_) => true,
        Type::SequenceOf(inner) | Type::SetOf(inner) => type_has_lifetime(inner, types),
    }
}

fn builtin_has_lifetime(b: Builtin) -> bool {
    !matches!(b, Builtin::Boolean | Builtin::Null)
}

fn builtin_core_name(b: Builtin) -> &'static str {
    match b {
        Builtin::Boolean => "Boolean",
        Builtin::Integer => "Integer",
        Builtin::BitString => "BitString",
        Builtin::OctetString => "OctetString",
        Builtin::Null => "Null",
        Builtin::ObjectIdentifier => "ObjectIdentifier",
        Builtin::RelativeOid => "RelativeOid",
        Builtin::Utf8String => "Utf8String",
        Builtin::NumericString => "NumericString",
        Builtin::PrintableString => "PrintableString",
        Builtin::TeletexString => "TeletexString",
        Builtin::VideotexString => "VideotexString",
        Builtin::Ia5String => "Ia5String",
        Builtin::UtcTime => "UtcTime",
        Builtin::GeneralizedTime => "GeneralizedTime",
        Builtin::GraphicString => "GraphicString",
        Builtin::VisibleString => "VisibleString",
        Builtin::GeneralString => "GeneralString",
        Builtin::UniversalString => "UniversalString",
        Builtin::CharacterString => "CharacterString",
        Builtin::BmpString => "BmpString",
        Builtin::ObjectDescriptor => "ObjectDescriptor",
    }
}

fn builtin_tag_variant(b: Builtin) -> &'static str {
    match b {
        Builtin::Boolean => "BOOLEAN",
        Builtin::Integer => "INTEGER",
        Builtin::BitString => "BIT_STRING",
        Builtin::OctetString => "OCTET_STRING",
        Builtin::Null => "NULL",
        Builtin::ObjectIdentifier => "OBJECT_IDENTIFIER",
        Builtin::RelativeOid => "RELATIVE_OID",
        Builtin::Utf8String => "UTF8_STRING",
        Builtin::NumericString => "NUMERIC_STRING",
        Builtin::PrintableString => "PRINTABLE_STRING",
        Builtin::TeletexString => "TELETEX_STRING",
        Builtin::VideotexString => "VIDEOTEX_STRING",
        Builtin::Ia5String => "IA5_STRING",
        Builtin::UtcTime => "UTC_TIME",
        Builtin::GeneralizedTime => "GENERALIZED_TIME",
        Builtin::GraphicString => "GRAPHIC_STRING",
        Builtin::VisibleString => "VISIBLE_STRING",
        Builtin::GeneralString => "GENERAL_STRING",
        Builtin::UniversalString => "UNIVERSAL_STRING",
        Builtin::CharacterString => "CHARACTER_STRING",
        Builtin::BmpString => "BMP_STRING",
        Builtin::ObjectDescriptor => "OBJECT_DESCRIPTOR",
    }
}

fn is_constructed(ty: &Type, types: &[TypeAssignment]) -> bool {
    match ty {
        Type::Builtin(_) => false,
        Type::Named(name) => def_is_constructed(lookup(name, types).unwrap(), types),
        Type::Sequence(_) | Type::Set(_) | Type::Choice(_) => true,
        Type::SequenceOf(_) | Type::SetOf(_) => true,
    }
}

fn def_is_constructed(def: &TypeDef, types: &[TypeAssignment]) -> bool {
    match def {
        TypeDef::Sequence(_) | TypeDef::Set(_) | TypeDef::Choice(_) => true,
        TypeDef::Enumerated(_) => false,
        TypeDef::Alias(t) => is_constructed(t, types),
    }
}

fn is_seqof(ty: &Type, types: &[TypeAssignment]) -> Option<&'static str> {
    match ty {
        Type::SequenceOf(_) => Some("SEQUENCE"),
        Type::SetOf(_) => Some("SET"),
        Type::Named(name) => match lookup(name, types).unwrap() {
            TypeDef::Alias(Type::SequenceOf(_)) => Some("SEQUENCE"),
            TypeDef::Alias(Type::SetOf(_)) => Some("SET"),
            TypeDef::Alias(t) => is_seqof(t, types),
            _ => None,
        },
        Type::Sequence(_) | Type::Set(_) | Type::Choice(_) | Type::Builtin(_) => None,
    }
}

/// Resolve a possibly-aliased type down to a `SequenceOf`/`SetOf`, returning
/// the inner type and the SET/SEQUENCE kind.
fn seqof_inner<'a>(ty: &'a Type, types: &'a [TypeAssignment]) -> Option<(&'a Type, &'static str)> {
    match ty {
        Type::SequenceOf(inner) => Some((inner, "SEQUENCE")),
        Type::SetOf(inner) => Some((inner, "SET")),
        Type::Named(name) => match lookup(name, types).unwrap() {
            TypeDef::Alias(Type::SequenceOf(inner)) => Some((inner, "SEQUENCE")),
            TypeDef::Alias(Type::SetOf(inner)) => Some((inner, "SET")),
            TypeDef::Alias(t) => seqof_inner(t, types),
            _ => None,
        },
        _ => None,
    }
}

fn rust_type(ty: &Type, types: &[TypeAssignment]) -> String {
    match ty {
        Type::Named(name) => {
            let lf = def_has_lifetime(lookup(name, types).unwrap(), types);
            if lf {
                format!("{name}<'a>")
            } else {
                name.clone()
            }
        }
        Type::Builtin(b) => {
            let n = builtin_core_name(*b);
            if builtin_has_lifetime(*b) {
                format!("{n}<'a>")
            } else {
                n.to_string()
            }
        }
        Type::Sequence(_) | Type::Set(_) | Type::Choice(_) => {
            unreachable!("compound types are always named")
        }
        Type::SequenceOf(inner) => {
            let inner_ty = rust_type(inner, types);
            format!("Vec<{inner_ty}>")
        }
        Type::SetOf(inner) => {
            let inner_ty = rust_type(inner, types);
            format!("Vec<{inner_ty}>")
        }
    }
}

fn to_snake(name: &str) -> String {
    let mut out = String::new();
    let mut prev_lower = false;
    for (i, c) in name.chars().enumerate() {
        if c.is_uppercase() && i > 0 && prev_lower {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
        prev_lower = c.is_lowercase() || c.is_ascii_digit();
    }
    out
}

fn to_pascal(name: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in name.chars() {
        if c == '-' || c == '_' || c == ' ' {
            upper = true;
            continue;
        }
        if upper {
            out.push(c.to_ascii_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn natural_tag_expr(ty: &Type, types: &[TypeAssignment]) -> String {
    match ty {
        Type::Builtin(b) => format!("Tag::universal(Tag::{})", builtin_tag_variant(*b)),
        Type::Named(name) => natural_tag_of_def(lookup(name, types).unwrap(), types),
        Type::SequenceOf(_) | Type::SetOf(_) => "Tag::universal_constructed(Tag::SEQUENCE)".to_string(),
        Type::Sequence(_) | Type::Set(_) | Type::Choice(_) => {
            unreachable!("compound types are always named")
        }
    }
}

fn natural_tag_of_def(def: &TypeDef, types: &[TypeAssignment]) -> String {
    match def {
        TypeDef::Sequence(_) => "Tag::universal_constructed(Tag::SEQUENCE)".to_string(),
        TypeDef::Set(_) => "Tag::universal_constructed(Tag::SET)".to_string(),
        TypeDef::Enumerated(_) => "Tag::universal(Tag::ENUMERATED)".to_string(),
        TypeDef::Alias(t) => natural_tag_expr(t, types),
        TypeDef::Choice(_) => "Tag::universal(Tag::SEQUENCE)".to_string(), // placeholder; unused
    }
}

fn tag_expr_for_spec(spec: &TagSpec, ty: &Type, types: &[TypeAssignment]) -> String {
    let cls = match spec.class {
        TagClass::Universal => "Universal",
        TagClass::Application => "Application",
        TagClass::Context => "Context",
        TagClass::Private => "Private",
    };
    let constructed = if spec.explicit {
        true
    } else {
        is_constructed(ty, types)
    };
    format!("Tag::new(Class::{cls}, {constructed}, {})", spec.number)
}

fn field_tag_expr(field: &Field, types: &[TypeAssignment]) -> String {
    match &field.tagging {
        Tagging::None => natural_tag_expr(&field.ty, types),
        Tagging::Tagged(spec) => tag_expr_for_spec(spec, &field.ty, types),
    }
}

fn resolve_choice(field: &Field, types: &[TypeAssignment]) -> Option<String> {
    match &field.ty {
        Type::Named(name) => match lookup(name, types) {
            Some(TypeDef::Choice(_)) => Some(name.clone()),
            Some(TypeDef::Alias(t)) => resolve_choice_inner(t, types),
            _ => None,
        },
        _ => resolve_choice_inner(&field.ty, types),
    }
}

fn resolve_choice_inner(ty: &Type, types: &[TypeAssignment]) -> Option<String> {
    match ty {
        Type::Named(name) => match lookup(name, types) {
            Some(TypeDef::Choice(_)) => Some(name.clone()),
            Some(TypeDef::Alias(t)) => resolve_choice_inner(t, types),
            _ => None,
        },
        Type::Choice(_) => None, // anonymous; unsupported as a field
        _ => None,
    }
}

fn generate_type(name: &str, def: &TypeDef, types: &[TypeAssignment]) -> Result<String> {
    let rust_name = to_pascal(name);
    let lf = def_has_lifetime(def, types);
    let lifetime = if lf { "<'a>" } else { "" };
    let lifetime_param = if lf { "<'a>" } else { "" };

    match def {
        TypeDef::Enumerated(vars) => Ok(generate_enumerated(&rust_name, vars)),
        TypeDef::Sequence(fields) => {
            generate_struct(&rust_name, lifetime, lifetime_param, fields, types, false)
        }
        TypeDef::Set(fields) => {
            generate_struct(&rust_name, lifetime, lifetime_param, fields, types, true)
        }
        TypeDef::Choice(fields) => generate_choice(&rust_name, lifetime, lifetime_param, fields, types),
        TypeDef::Alias(ty) => {
            let inner = rust_type(ty, types);
            Ok(format!("pub type {rust_name}{lifetime_param} = {inner};\n"))
        }
    }
}

fn generate_enumerated(name: &str, vars: &[EnumVariant]) -> String {
    let mut out = String::new();
    out.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    out.push_str(&format!("pub enum {name} {{\n"));
    for v in vars {
        out.push_str(&format!("    {},\n", to_pascal(&v.name)));
    }
    out.push_str("}\n\n");

    out.push_str(&format!("impl<'a> {name} {{\n"));
    out.push_str(&format!(
        "    pub fn decode_content(r: &mut Reader<'a>) -> Result<Self> {{\n        let __b = r.read_remaining()?;\n        {name}::from_content(__b)\n    }}\n"
    ));
    out.push_str(&format!(
        "    fn from_content(__b: &[u8]) -> Result<Self> {{\n        let __v = Integer(__b).as_i64().ok_or(Error::Custom(\"invalid ENUMERATED\"))?;\n        match __v {{\n"
    ));
    for v in vars {
        out.push_str(&format!(
            "            {} => Ok({}::{}),\n",
            v.number,
            name,
            to_pascal(&v.name)
        ));
    }
    out.push_str(&format!(
        "            _ => Err(Error::Custom(\"unknown {name} enumerant\")),\n        }}\n    }}\n}}\n\n"
    ));

    out.push_str(&format!("impl<'a> Decode<'a> for {name} {{\n"));
    out.push_str(&format!(
        "    fn decode(r: &mut Reader<'a>) -> Result<Self> {{\n        let __b = read_primitive(r, Tag::universal(Tag::ENUMERATED))?;\n        {name}::from_content(__b)\n    }}\n}}\n\n"
    ));

    out.push_str(&format!("impl Encode for {name} {{\n"));
    out.push_str(&format!("    fn encode<W: WriteBackend>(&self, w: &mut Writer<W>) -> Result<()> {{\n"));
    out.push_str("        let __v: i64 = match self {\n");
    for v in vars {
        out.push_str(&format!("            {}::{} => {},\n", name, to_pascal(&v.name), v.number));
    }
    out.push_str("        };\n");
    out.push_str("        let mut __buf = [0u8; 9];\n");
    out.push_str(
        "        let __n = tpt_asn1_core::util::encode_signed_integer(__v, &mut __buf);\n",
    );
    out.push_str("        w.write_primitive(Tag::universal(Tag::ENUMERATED), &__buf[..__n])\n");
    out.push_str("    }\n}\n");
    out
}

fn generate_struct(
    name: &str,
    _lifetime: &str,
    lifetime_param: &str,
    fields: &[Field],
    types: &[TypeAssignment],
    is_set: bool,
) -> Result<String> {
    let read_fn = if is_set { "read_set" } else { "read_sequence" };
    let seq_tag = if is_set {
        "Tag::universal_constructed(Tag::SET)"
    } else {
        "Tag::universal_constructed(Tag::SEQUENCE)"
    };

    let mut out = String::new();
    out.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    out.push_str(&format!("pub struct {name}{lifetime_param} {{\n"));
    for f in fields {
        let fname = to_snake(&f.name);
        let is_opt = f.optional || f.default.is_some();
        let base = rust_type(&f.ty, types);
        let fty = if is_opt { format!("Option<{base}>") } else { base };
        out.push_str(&format!("    pub {fname}: {fty},\n"));
    }
    out.push_str("}\n\n");

    // decode_content
    out.push_str(&format!("impl{lifetime_param} {name}{lifetime_param} {{\n"));
    out.push_str(&format!(
        "    pub fn decode_content(r: &mut Reader<'a>) -> Result<Self> {{\n        let mut __items: Vec<Any> = Vec::new();\n        while !r.is_empty() {{\n            __items.push(Any::decode(r)?);\n        }}\n        let mut __cur = 0usize;\n        let __n = __items.len();\n        let __cfg = *r.config();\n"
    ));

    let mut final_inits = Vec::new();
    for f in fields {
        let fname = to_snake(&f.name);
        let is_opt = f.optional || f.default.is_some();
        let base = rust_type(&f.ty, types);
        let decode_call = decode_via_any(f, types)?;
        let match_expr = if resolve_choice(f, types).is_some() && matches!(f.tagging, Tagging::None) {
            let choice_name = resolve_choice(f, types).unwrap();
            format!("{choice_name}::is_alternative_tag(__a.tag)")
        } else {
            format!("__a.tag == {}", field_tag_expr(f, types))
        };

        out.push_str(&format!("        let mut {fname}: Option<{base}> = None;\n"));
        out.push_str(&format!("        if __cur < __n {{\n            let __a = &__items[__cur];\n"));
        out.push_str(&format!("            if {match_expr} {{\n"));
        out.push_str(&format!("                {fname} = Some({decode_call});\n"));
        out.push_str("                __cur += 1;\n");
        out.push_str("            }\n        }\n");

        if !is_opt {
            out.push_str(&format!(
                "        let {fname} = {fname}.ok_or(Error::Custom(\"missing required field `{fname}`\"))?;\n"
            ));
            final_inits.push(format!("{fname}"));
        } else {
            final_inits.push(format!("{fname}"));
        }
    }

    out.push_str("        if __cur != __n {\n            return Err(Error::Custom(\"unexpected trailing field\"));\n        }\n");
    out.push_str(&format!("        Ok({name} {{\n"));
    for fi in &final_inits {
        out.push_str(&format!("            {fi},\n"));
    }
    out.push_str("        })\n    }\n}\n\n");

    // Decode impl
    out.push_str(&format!("impl{lifetime_param} Decode<'a> for {name}{lifetime_param} {{\n"));
    out.push_str(&format!(
        "    fn decode(r: &mut Reader<'a>) -> Result<Self> {{\n        {read_fn}(r, |r| {name}{lifetime_param}::decode_content(r))\n    }}\n}}\n\n"
    ));

    // Encode impl
    out.push_str(&format!("impl{lifetime_param} Encode for {name}{lifetime_param} {{\n"));
    out.push_str(&format!(
        "    fn encode<W: WriteBackend>(&self, w: &mut Writer<W>) -> Result<()> {{\n        w.nested({seq_tag}, |w| {{\n"
    ));
    for f in fields {
        let fname = to_snake(&f.name);
        let is_opt = f.optional || f.default.is_some();
        let encode_body = encode_value(&format!("__v"), f, types)?;
        if is_opt {
            out.push_str(&format!("            if let Some(__v) = &self.{fname} {{\n"));
            if let Some(dv) = &f.default {
                let check = default_eq_expr(dv);
                out.push_str(&format!("                if !({check}) {{\n"));
                out.push_str(&format!("                {encode_body}\n"));
                out.push_str("                }\n");
            } else {
                out.push_str(&format!("                {encode_body}\n"));
            }
            out.push_str("            }\n");
        } else {
            out.push_str(&format!("            {{\n                let __v = &self.{fname};\n                {encode_body}\n            }}\n"));
        }
    }
    out.push_str("            Ok(())\n        })\n    }\n}\n");
    Ok(out)
}

fn decode_via_any(field: &Field, types: &[TypeAssignment]) -> Result<String> {
    if let Some(choice_name) = resolve_choice(field, types) {
        return if matches!(field.tagging, Tagging::None) {
            Ok(format!("{choice_name}::decode_from_any(__a, __cfg)?"))
        } else {
            // Tagged CHOICE: the field tag wraps the full alternative TLV in its
            // value; decode the CHOICE from that value.
            Ok(format!("{choice_name}::decode(&mut Reader::new(__a.value, __cfg))?"))
        };
    }
    let base = rust_type(&field.ty, types);
    match &field.tagging {
        Tagging::None => {
            if let Some((_inner, kind)) = seqof_inner(&field.ty, types) {
                if kind == "SET" {
                    Ok("read_set_of(&mut Reader::new(__a.full, __cfg))?".to_string())
                } else {
                    Ok("read_sequence_of(&mut Reader::new(__a.full, __cfg))?".to_string())
                }
            } else {
                Ok(format!("<{base}>::decode(&mut Reader::new(__a.full, __cfg))?"))
            }
        }
        Tagging::Tagged(spec) => {
            if spec.explicit {
                if let Some((_inner, kind)) = seqof_inner(&field.ty, types) {
                    if kind == "SET" {
                        Ok("read_set_of(&mut Reader::new(__a.value, __cfg))?".to_string())
                    } else {
                        Ok("read_sequence_of(&mut Reader::new(__a.value, __cfg))?".to_string())
                    }
                } else {
                    Ok(format!("<{base}>::decode(&mut Reader::new(__a.value, __cfg))?"))
                }
            } else if let Some((_inner, kind)) = seqof_inner(&field.ty, types) {
                if kind == "SET" {
                    Ok("read_set_of_content(&mut Reader::new(__a.value, __cfg))?".to_string())
                } else {
                    Ok("read_sequence_of_content(&mut Reader::new(__a.value, __cfg))?".to_string())
                }
            } else {
                Ok(format!(
                    "<{base}>::decode_content(&mut Reader::new(__a.value, __cfg))?"
                ))
            }
        }
    }
}

fn encode_value(value: &str, field: &Field, types: &[TypeAssignment]) -> Result<String> {
    let is_seq = is_seqof(&field.ty, types).is_some();
    let is_choice = resolve_choice(field, types).is_some();
    match &field.tagging {
        Tagging::None => {
            if is_seq {
                let kind = is_seqof(&field.ty, types).unwrap();
                Ok(seqof_encode(value, kind, None))
            } else {
                Ok(format!("{value}.encode(w)?;"))
            }
        }
        Tagging::Tagged(spec) => {
            let tag = tag_expr_for_spec(spec, &field.ty, types);
            if is_seq {
                let kind = is_seqof(&field.ty, types).unwrap();
                let seq_tag = if kind == "SET" {
                    "Tag::universal_constructed(Tag::SET)"
                } else {
                    "Tag::universal_constructed(Tag::SEQUENCE)"
                };
                if spec.explicit {
                    // Build the inner SEQUENCE/SET TLV, then wrap it in the tag.
                    Ok(format!(
                        "let mut __tmp = Writer::new_vec();\n                __tmp.nested({seq_tag}, |__w| {{ for __e in {value}.iter() {{ __e.encode(__w)?; }} Ok(()) }})?;\n                let __tmp = __tmp.into_vec();\n                w.nested({tag}, |__w| __w.write_bytes(&__tmp))?;"
                    ))
                } else {
                    Ok(seqof_encode(value, kind, Some(&tag)))
                }
            } else if is_choice {
                // A CHOICE has no natural tag, so IMPLICIT behaves like
                // EXPLICIT: wrap the full alternative TLV in the field tag.
                Ok(format!(
                    "let __tmp = encode_to_vec(&{value})?;\n                w.nested({tag}, |__w| __w.write_bytes(&__tmp))?;"
                ))
            } else if spec.explicit {
                Ok(format!(
                    "let __tmp = encode_to_vec(&{value})?;\n                w.nested({tag}, |__w| __w.write_bytes(&__tmp))?;"
                ))
            } else {
                Ok(format!(
                    "let __tmp = encode_to_vec(&{value})?;\n                let __tagged = retag_implicit(&__tmp, {tag})?;\n                w.write_bytes(&__tagged)?;"
                ))
            }
        }
    }
}

fn seqof_encode(value: &str, kind: &str, tag: Option<&str>) -> String {
    let seq_tag = if kind == "SET" {
        "Tag::universal_constructed(Tag::SET)"
    } else {
        "Tag::universal_constructed(Tag::SEQUENCE)"
    };
    let inner = format!(
        "let mut __tmp = Writer::new_vec();\n                __tmp.nested({seq_tag}, |__w| {{ for __e in {value}.iter() {{ __e.encode(__w)?; }} Ok(()) }})?;\n                let __tmp = __tmp.into_vec();"
    );
    match tag {
        None => format!(
            "{inner}\n                w.write_bytes(&__tmp)?;"
        ),
        Some(t) => format!(
            "{inner}\n                let __tagged = retag_implicit(&__tmp, {t})?;\n                w.write_bytes(&__tagged)?;"
        ),
    }
}

fn default_eq_expr(dv: &DefaultValue) -> String {
    match dv {
        DefaultValue::Boolean(b) => format!("__v.0 == {b}"),
        DefaultValue::Integer(n) => format!("__v.as_i64() == Some({n})"),
        DefaultValue::Null => "true".to_string(),
    }
}

fn generate_choice(
    name: &str,
    _lifetime: &str,
    lifetime_param: &str,
    fields: &[Field],
    types: &[TypeAssignment],
) -> Result<String> {
    let mut out = String::new();
    for f in fields {
        if resolve_choice(f, types).is_some() {
            return Err(CompilerError::codegen(
                "nested CHOICE alternatives are not supported in this release",
            ));
        }
    }
    out.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    out.push_str(&format!("pub enum {name}{lifetime_param} {{\n"));
    for f in fields {
        let vname = to_pascal(&f.name);
        let vty = rust_type(&f.ty, types);
        out.push_str(&format!("    {vname}({vty}),\n"));
    }
    out.push_str("}\n\n");

    // decode_content + decode_from_any + is_alternative_tag
    out.push_str(&format!("impl{lifetime_param} {name}{lifetime_param} {{\n"));
    out.push_str(&format!(
        "    pub fn decode_content(r: &mut Reader<'a>) -> Result<Self> {{\n        let __any = Any::decode(r)?;\n        {name}::decode_from_any(&__any, *r.config())\n    }}\n"
    ));
    out.push_str(&format!(
        "    pub fn is_alternative_tag(tag: Tag) -> bool {{\n        {}\n    }}\n",
        fields
            .iter()
            .map(|f| format!("tag == {}", alt_tag_expr(f, types)))
            .collect::<Vec<_>>()
            .join(" ||\n        ")
    ));
    out.push_str(&format!(
        "    pub fn decode_from_any(__any: &Any, __cfg: Config) -> Result<Self> {{\n"
    ));
    for f in fields {
        let vname = to_pascal(&f.name);
        let decode_call = alt_decode_call(f, types)?;
        out.push_str(&format!(
            "        if __any.tag == {} {{\n            return Ok({name}::{vname}({decode_call}));\n        }}\n",
            alt_tag_expr(f, types)
        ));
    }
    out.push_str(&format!(
        "        Err(Error::Custom(\"unknown {name} CHOICE alternative\"))\n    }}\n}}\n\n"
    ));

    // Decode impl
    out.push_str(&format!("impl{lifetime_param} Decode<'a> for {name}{lifetime_param} {{\n"));
    out.push_str(&format!(
        "    fn decode(r: &mut Reader<'a>) -> Result<Self> {{\n        let __any = Any::decode(r)?;\n        {name}::decode_from_any(&__any, *r.config())\n    }}\n}}\n\n"
    ));

    // Encode impl
    out.push_str(&format!("impl{lifetime_param} Encode for {name}{lifetime_param} {{\n"));
    out.push_str(&format!("    fn encode<W: WriteBackend>(&self, w: &mut Writer<W>) -> Result<()> {{\n        match self {{\n"));
    for f in fields {
        let vname = to_pascal(&f.name);
        let encode_body = encode_value("__v", f, types)?;
        out.push_str(&format!("            {name}::{vname}(__v) => {{\n                {encode_body}\n            }}\n"));
    }
    out.push_str("        }\n        Ok(())\n    }\n}\n");
    Ok(out)
}

fn alt_tag_expr(field: &Field, types: &[TypeAssignment]) -> String {
    match &field.tagging {
        Tagging::None => {
            if resolve_choice(field, types).is_some() {
                // nested choice: delegate to its tag predicate
                if let Some(cn) = resolve_choice(field, types) {
                    return format!("{cn}::is_alternative_tag");
                }
            }
            natural_tag_expr(&field.ty, types)
        }
        Tagging::Tagged(spec) => tag_expr_for_spec(spec, &field.ty, types),
    }
}

fn alt_decode_call(field: &Field, types: &[TypeAssignment]) -> Result<String> {
    let base = rust_type(&field.ty, types);
    match &field.tagging {
        Tagging::None => {
            if resolve_choice(field, types).is_some() {
                Ok(format!("{base}::decode(&mut Reader::new(__any.full, __cfg))?"))
            } else {
                Ok(format!("<{base}>::decode(&mut Reader::new(__any.full, __cfg))?"))
            }
        }
        Tagging::Tagged(spec) => {
            if spec.explicit {
                Ok(format!("<{base}>::decode(&mut Reader::new(__any.value, __cfg))?"))
            } else {
                Ok(format!("<{base}>::decode_content(&mut Reader::new(__any.value, __cfg))?"))
            }
        }
    }
}
