// Generated by tpt-asn1-compiler from module `ExamplePKI`. Do not edit.
#![allow(unused_imports, non_camel_case_types, unused_lifetimes, clippy::all)]
use tpt_asn1_core::{
    reader::{Reader, EncodingRule, Config},
    decode::{Decode, Encode, read_sequence, read_set, read_sequence_of, read_set_of, read_sequence_of_content, read_set_of_content, retag_implicit, encode_to_vec},
    tag::{Tag, Class},
    writer::{Writer, WriteBackend},
    types::*,
    any::Any,
    error::{Error, Result},
    length::Length,
    Vec,
};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AlgorithmIdentifier<'a> {
    pub algorithm: ObjectIdentifier<'a>,
    pub parameters: Option<Null>,
}

impl<'a> AlgorithmIdentifier<'a> {
    pub fn decode_content(r: &mut Reader<'a>) -> Result<Self> {
        let mut __items: Vec<Any> = Vec::new();
        while !r.is_empty() {
            __items.push(Any::decode(r)?);
        }
        let mut __cur = 0usize;
        let __n = __items.len();
        let __cfg = *r.config();
        let mut algorithm: Option<ObjectIdentifier<'a>> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::universal(Tag::OBJECT_IDENTIFIER) {
                algorithm = Some(<ObjectIdentifier<'a>>::decode(&mut Reader::new(__a.full, __cfg))?);
                __cur += 1;
            }
        }
        let algorithm = algorithm.ok_or(Error::Custom("missing required field `algorithm`"))?;
        let mut parameters: Option<Null> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::universal(Tag::NULL) {
                parameters = Some(<Null>::decode(&mut Reader::new(__a.full, __cfg))?);
                __cur += 1;
            }
        }
        if __cur != __n {
            return Err(Error::Custom("unexpected trailing field"));
        }
        Ok(AlgorithmIdentifier {
            algorithm,
            parameters,
        })
    }
}

impl<'a> Decode<'a> for AlgorithmIdentifier<'a> {
    fn decode(r: &mut Reader<'a>) -> Result<Self> {
        read_sequence(r, |r| AlgorithmIdentifier<'a>::decode_content(r))
    }
}

impl<'a> Encode for AlgorithmIdentifier<'a> {
    fn encode<W: WriteBackend>(&self, w: &mut Writer<W>) -> Result<()> {
        w.nested(Tag::universal_constructed(Tag::SEQUENCE), |w| {
            {
                let __v = &self.algorithm;
                __v.encode(w)?;
            }
            if let Some(__v) = &self.parameters {
                __v.encode(w)?;
            }
            Ok(())
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Color {
    Red,
    Green,
    Blue,
}

impl<'a> Color {
    pub fn decode_content(r: &mut Reader<'a>) -> Result<Self> {
        let __b = r.read_remaining()?;
        Color::from_content(__b)
    }
    fn from_content(__b: &[u8]) -> Result<Self> {
        let __v = Integer(__b).as_i64().ok_or(Error::Custom("invalid ENUMERATED"))?;
        match __v {
            0 => Ok(Color::Red),
            1 => Ok(Color::Green),
            2 => Ok(Color::Blue),
            _ => Err(Error::Custom("unknown Color enumerant")),
        }
    }
}

impl<'a> Decode<'a> for Color {
    fn decode(r: &mut Reader<'a>) -> Result<Self> {
        let __b = read_primitive(r, Tag::universal(Tag::ENUMERATED))?;
        Color::from_content(__b)
    }
}

impl Encode for Color {
    fn encode<W: WriteBackend>(&self, w: &mut Writer<W>) -> Result<()> {
        let __v: i64 = match self {
            Color::Red => 0,
            Color::Green => 1,
            Color::Blue => 2,
        };
        let mut __buf = [0u8; 9];
        let __n = tpt_asn1_core::util::encode_signed_integer(__v, &mut __buf);
        w.write_primitive(Tag::universal(Tag::ENUMERATED), &__buf[..__n])
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AttributeTypeAndValue<'a> {
    pub type: ObjectIdentifier<'a>,
    pub value: Utf8String<'a>,
}

impl<'a> AttributeTypeAndValue<'a> {
    pub fn decode_content(r: &mut Reader<'a>) -> Result<Self> {
        let mut __items: Vec<Any> = Vec::new();
        while !r.is_empty() {
            __items.push(Any::decode(r)?);
        }
        let mut __cur = 0usize;
        let __n = __items.len();
        let __cfg = *r.config();
        let mut type: Option<ObjectIdentifier<'a>> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::universal(Tag::OBJECT_IDENTIFIER) {
                type = Some(<ObjectIdentifier<'a>>::decode(&mut Reader::new(__a.full, __cfg))?);
                __cur += 1;
            }
        }
        let type = type.ok_or(Error::Custom("missing required field `type`"))?;
        let mut value: Option<Utf8String<'a>> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::universal(Tag::UTF8_STRING) {
                value = Some(<Utf8String<'a>>::decode(&mut Reader::new(__a.full, __cfg))?);
                __cur += 1;
            }
        }
        let value = value.ok_or(Error::Custom("missing required field `value`"))?;
        if __cur != __n {
            return Err(Error::Custom("unexpected trailing field"));
        }
        Ok(AttributeTypeAndValue {
            type,
            value,
        })
    }
}

impl<'a> Decode<'a> for AttributeTypeAndValue<'a> {
    fn decode(r: &mut Reader<'a>) -> Result<Self> {
        read_sequence(r, |r| AttributeTypeAndValue<'a>::decode_content(r))
    }
}

impl<'a> Encode for AttributeTypeAndValue<'a> {
    fn encode<W: WriteBackend>(&self, w: &mut Writer<W>) -> Result<()> {
        w.nested(Tag::universal_constructed(Tag::SEQUENCE), |w| {
            {
                let __v = &self.type;
                __v.encode(w)?;
            }
            {
                let __v = &self.value;
                __v.encode(w)?;
            }
            Ok(())
        })
    }
}

pub type RelativeDistinguishedName<'a> = Vec<AttributeTypeAndValue<'a>>;

pub type Name<'a> = Vec<RelativeDistinguishedName<'a>>;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SubjectPublicKeyInfo<'a> {
    pub algorithm: AlgorithmIdentifier<'a>,
    pub subject_public_key: BitString<'a>,
    pub critical_flag: Option<Boolean>,
    pub custom_data: Option<OctetString<'a>>,
    pub extensions: Vec<ObjectIdentifier<'a>>,
}

impl<'a> SubjectPublicKeyInfo<'a> {
    pub fn decode_content(r: &mut Reader<'a>) -> Result<Self> {
        let mut __items: Vec<Any> = Vec::new();
        while !r.is_empty() {
            __items.push(Any::decode(r)?);
        }
        let mut __cur = 0usize;
        let __n = __items.len();
        let __cfg = *r.config();
        let mut algorithm: Option<AlgorithmIdentifier<'a>> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::universal_constructed(Tag::SEQUENCE) {
                algorithm = Some(<AlgorithmIdentifier<'a>>::decode(&mut Reader::new(__a.full, __cfg))?);
                __cur += 1;
            }
        }
        let algorithm = algorithm.ok_or(Error::Custom("missing required field `algorithm`"))?;
        let mut subject_public_key: Option<BitString<'a>> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::universal(Tag::BIT_STRING) {
                subject_public_key = Some(<BitString<'a>>::decode(&mut Reader::new(__a.full, __cfg))?);
                __cur += 1;
            }
        }
        let subject_public_key = subject_public_key.ok_or(Error::Custom("missing required field `subject_public_key`"))?;
        let mut critical_flag: Option<Boolean> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::new(Class::Context, false, 0) {
                critical_flag = Some(<Boolean>::decode_content(&mut Reader::new(__a.value, __cfg))?);
                __cur += 1;
            }
        }
        let mut custom_data: Option<OctetString<'a>> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::new(Class::Context, true, 1) {
                custom_data = Some(<OctetString<'a>>::decode(&mut Reader::new(__a.value, __cfg))?);
                __cur += 1;
            }
        }
        let mut extensions: Option<Vec<ObjectIdentifier<'a>>> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::new(Class::Context, true, 2) {
                extensions = Some(read_sequence_of_content(&mut Reader::new(__a.value, __cfg))?);
                __cur += 1;
            }
        }
        let extensions = extensions.ok_or(Error::Custom("missing required field `extensions`"))?;
        if __cur != __n {
            return Err(Error::Custom("unexpected trailing field"));
        }
        Ok(SubjectPublicKeyInfo {
            algorithm,
            subject_public_key,
            critical_flag,
            custom_data,
            extensions,
        })
    }
}

impl<'a> Decode<'a> for SubjectPublicKeyInfo<'a> {
    fn decode(r: &mut Reader<'a>) -> Result<Self> {
        read_sequence(r, |r| SubjectPublicKeyInfo<'a>::decode_content(r))
    }
}

impl<'a> Encode for SubjectPublicKeyInfo<'a> {
    fn encode<W: WriteBackend>(&self, w: &mut Writer<W>) -> Result<()> {
        w.nested(Tag::universal_constructed(Tag::SEQUENCE), |w| {
            {
                let __v = &self.algorithm;
                __v.encode(w)?;
            }
            {
                let __v = &self.subject_public_key;
                __v.encode(w)?;
            }
            if let Some(__v) = &self.critical_flag {
                if !(__v.0 == false) {
                let __tmp = encode_to_vec(&__v)?;
                let __tagged = retag_implicit(&__tmp, Tag::new(Class::Context, false, 0))?;
                w.write_bytes(&__tagged)?;
                }
            }
            if let Some(__v) = &self.custom_data {
                let __tmp = encode_to_vec(&__v)?;
                w.nested(Tag::new(Class::Context, true, 1), |__w| __w.write_bytes(&__tmp))?;
            }
            {
                let __v = &self.extensions;
                let mut __tmp = Writer::new_vec();
                __tmp.nested(Tag::universal_constructed(Tag::SEQUENCE), |__w| { for __e in __v.iter() { __e.encode(__w)?; } Ok(()) })?;
                let __tmp = __tmp.into_vec();
                let __tagged = retag_implicit(&__tmp, Tag::new(Class::Context, true, 2))?;
                w.write_bytes(&__tagged)?;
            }
            Ok(())
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Extension<'a> {
    pub extn_id: ObjectIdentifier<'a>,
    pub critical: Option<Boolean>,
    pub extn_value: OctetString<'a>,
}

impl<'a> Extension<'a> {
    pub fn decode_content(r: &mut Reader<'a>) -> Result<Self> {
        let mut __items: Vec<Any> = Vec::new();
        while !r.is_empty() {
            __items.push(Any::decode(r)?);
        }
        let mut __cur = 0usize;
        let __n = __items.len();
        let __cfg = *r.config();
        let mut extn_id: Option<ObjectIdentifier<'a>> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::universal(Tag::OBJECT_IDENTIFIER) {
                extn_id = Some(<ObjectIdentifier<'a>>::decode(&mut Reader::new(__a.full, __cfg))?);
                __cur += 1;
            }
        }
        let extn_id = extn_id.ok_or(Error::Custom("missing required field `extn_id`"))?;
        let mut critical: Option<Boolean> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::universal(Tag::BOOLEAN) {
                critical = Some(<Boolean>::decode(&mut Reader::new(__a.full, __cfg))?);
                __cur += 1;
            }
        }
        let mut extn_value: Option<OctetString<'a>> = None;
        if __cur < __n {
            let __a = &__items[__cur];
            if __a.tag == Tag::universal(Tag::OCTET_STRING) {
                extn_value = Some(<OctetString<'a>>::decode(&mut Reader::new(__a.full, __cfg))?);
                __cur += 1;
            }
        }
        let extn_value = extn_value.ok_or(Error::Custom("missing required field `extn_value`"))?;
        if __cur != __n {
            return Err(Error::Custom("unexpected trailing field"));
        }
        Ok(Extension {
            extn_id,
            critical,
            extn_value,
        })
    }
}

impl<'a> Decode<'a> for Extension<'a> {
    fn decode(r: &mut Reader<'a>) -> Result<Self> {
        read_sequence(r, |r| Extension<'a>::decode_content(r))
    }
}

impl<'a> Encode for Extension<'a> {
    fn encode<W: WriteBackend>(&self, w: &mut Writer<W>) -> Result<()> {
        w.nested(Tag::universal_constructed(Tag::SEQUENCE), |w| {
            {
                let __v = &self.extn_id;
                __v.encode(w)?;
            }
            if let Some(__v) = &self.critical {
                if !(__v.0 == false) {
                __v.encode(w)?;
                }
            }
            {
                let __v = &self.extn_value;
                __v.encode(w)?;
            }
            Ok(())
        })
    }
}

pub type Extensions<'a> = Vec<Extension<'a>>;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GeneralName<'a> {
    DNSName(Ia5String<'a>),
    Rfc822Name(Ia5String<'a>),
    UniformResourceIdentifier(Ia5String<'a>),
    DirectoryName(Name<'a>),
}

impl<'a> GeneralName<'a> {
    pub fn decode_content(r: &mut Reader<'a>) -> Result<Self> {
        let __any = Any::decode(r)?;
        GeneralName::decode_from_any(&__any, *r.config())
    }
    pub fn is_alternative_tag(tag: Tag) -> bool {
        tag == Tag::new(Class::Context, false, 0) ||
        tag == Tag::new(Class::Context, false, 1) ||
        tag == Tag::new(Class::Context, false, 2) ||
        tag == Tag::new(Class::Context, true, 3)
    }
    pub fn decode_from_any(__any: &Any, __cfg: Config) -> Result<Self> {
        if __any.tag == Tag::new(Class::Context, false, 0) {
            return Ok(GeneralName::DNSName(<Ia5String<'a>>::decode_content(&mut Reader::new(__any.value, __cfg))?));
        }
        if __any.tag == Tag::new(Class::Context, false, 1) {
            return Ok(GeneralName::Rfc822Name(<Ia5String<'a>>::decode_content(&mut Reader::new(__any.value, __cfg))?));
        }
        if __any.tag == Tag::new(Class::Context, false, 2) {
            return Ok(GeneralName::UniformResourceIdentifier(<Ia5String<'a>>::decode_content(&mut Reader::new(__any.value, __cfg))?));
        }
        if __any.tag == Tag::new(Class::Context, true, 3) {
            return Ok(GeneralName::DirectoryName(<Name<'a>>::decode(&mut Reader::new(__any.value, __cfg))?));
        }
        Err(Error::Custom("unknown GeneralName CHOICE alternative"))
    }
}

impl<'a> Decode<'a> for GeneralName<'a> {
    fn decode(r: &mut Reader<'a>) -> Result<Self> {
        let __any = Any::decode(r)?;
        GeneralName::decode_from_any(&__any, *r.config())
    }
}

impl<'a> Encode for GeneralName<'a> {
    fn encode<W: WriteBackend>(&self, w: &mut Writer<W>) -> Result<()> {
        match self {
            GeneralName::DNSName(__v) => {
                let __tmp = encode_to_vec(&__v)?;
                let __tagged = retag_implicit(&__tmp, Tag::new(Class::Context, false, 0))?;
                w.write_bytes(&__tagged)?;
            }
            GeneralName::Rfc822Name(__v) => {
                let __tmp = encode_to_vec(&__v)?;
                let __tagged = retag_implicit(&__tmp, Tag::new(Class::Context, false, 1))?;
                w.write_bytes(&__tagged)?;
            }
            GeneralName::UniformResourceIdentifier(__v) => {
                let __tmp = encode_to_vec(&__v)?;
                let __tagged = retag_implicit(&__tmp, Tag::new(Class::Context, false, 2))?;
                w.write_bytes(&__tagged)?;
            }
            GeneralName::DirectoryName(__v) => {
                let mut __tmp = Writer::new_vec();
                __tmp.nested(Tag::universal_constructed(Tag::SEQUENCE), |__w| { for __e in __v.iter() { __e.encode(__w)?; } Ok(()) })?;
                let __tmp = __tmp.into_vec();
                w.nested(Tag::new(Class::Context, true, 3), |__w| __w.write_bytes(&__tmp))?;
            }
        }
        Ok(())
    }
}

pub type GeneralNames<'a> = Vec<GeneralName<'a>>;

pub type CertificateSerialNumber<'a> = Integer<'a>;

pub type SignatureValue<'a> = BitString<'a>;

